### ISSUE TITLE
No Values for bobcatminer every few days

### ISSUE THREAD

**Issue by nikolas22t** [ardevd/ha-bobcatminer#26] opened 2023-01-15 14:03 UTC
Every few days , the bobcat miner stops sync value with home assistant , i tried to add to another home assistant to check , and the result is the same , the device is working fine and the network between the two devices are monitored without any downtime , any advise ?

[https://ibb.co/NmjgZhs](url)

**Comment by ardevd** [comment] 2023-01-15 18:37
Is there anything in the logs that might give you a clue of what's happening? I can't reproduce the issue on my end. The reporting has been flawless with the latest version.

**Comment by BenBergman** [comment] 2023-02-12 19:28
I'm seeing something very similar - Home Assistant will pull in stats fine for a little bit, then nothing for days. The state stays stuck at "running" despite the device logbook in HA saying it has changed to "unknown" or "unavailable" every 30 minutes or so. Is that the log you meant or is there a different one to check?

**Comment by nikolas22t** [comment] 2023-02-12 19:39
Yes thats the issue

**Comment by ardevd** [comment] 2023-02-15 08:59
Thanks for the information. I'm still unable to reproduce this issue. I'd appreciate log output from the Home Assistant log. Accessible through Home Asssistant --> Settings --> System --> Logs. No need to provide full log output, but anything related to the Bobcat miner integration would be helpful.

**Comment by BenBergman** [comment] 2023-02-19 16:20
So I decided to look at the temperature sensor for the Bobcat and it seems to be reporting correctly at regular intervals. Looking at the Home Assistant system logs I see this bobcatminer related error occasionally:

```
2023-02-19 09:02:37.935 ERROR (MainThread) [custom_components.bobcatminer.coordinator] Error fetching bobcatminer data: Unable to update miner status: Rate limit exceeded, try again later
```

I'm guessing that error causes the device logbook to show the "unknown" status despite not updating the sensor. Maybe we just need a configuration item to adjust the update frequency, or just scale it back a bit globally.

**Comment by ardevd** [comment] 2023-02-20 07:35
Thanks for investigating. The bobcatminer's web diagnoser has a very aggressive rate limit which is hard to deal with when we have different platforms (button, sensor) that update independently of each other. I'll try to see if I can deal with the issue in a better way, but it's a good idea to make sure you don't have anything else polling the web diagnoser.

**Comment by ardevd** [comment] 2024-02-24 10:58
This should be fixed now, due to improvements to the diagnoser

**Closed as completed by ardevd** 2024-02-24 10:58 UTC
